version: 2
jobs:
  build:
    docker:
    - image: circleci/node:jessie-browsers
    working_directory: ~/repo
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "imasbook03/yarn.lock" }}
        - v1-dependencies-
    - run:
        name: build output.pdf
        command: |
          cd imasbook03
          yarn install
          yarn run build
    - save_cache:
        paths:
        - "imasbook03/node_modules"
        key: v1-dependencies-{{ checksum "imasbook03/yarn.lock" }}
    - store_artifacts:
        path: imasbook03/output.pdf
